cascade-withdrawal:
  topics: ml256/cascade/withdrawal
  tags: user
  fields: amount

cascade-bank:
  topics: ml256/cascade/bank
  fields: funds

cascade-error:
  topics: ml256/cascade/error
  tags: error
  fields: message
